# -*- coding: utf-8 -*-
"""Activation Function Comparison .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wi8A64EVIG26En_epQS1FQbVAj21XNP3

#  Activation Function Comparison: Gradient Flow & Training Dynamics

##  Objective

The goal of this notebook is to **systematically compare different activation functions** and understand their impact on:

* Gradient flow across deep networks
* Training speed and convergence
* Stability of optimization

---

##  Background

Activation functions introduce **non-linearity** into neural networks, enabling them to learn complex patterns.

However, they also directly influence:

* Gradient magnitude
* Learning dynamics
* Training stability

Poor choice of activation can lead to:

* Vanishing gradients
*  Exploding gradients
* Slow or failed convergence

---

##  Experiment Design

To ensure a fair comparison, we keep all factors constant:

* Same dataset
* Same deep architecture (10 layers)
* Same optimizer (SGD)
* Same learning rate
* Same training loop

###  Only variable changed:

> **Activation function**

---

## ⚙️ Activation Functions & Initialization Strategy

Different activations require different initialization methods for stable training:

| Activation Function | Output Range         | Problem                                     | Recommended Initialization  |
| ------------------- | -------------------- | ------------------------------------------- | --------------------------- |
| Sigmoid             | (0, 1)               | Strong vanishing gradients                  | Xavier Initialization       |
| Tanh                | (-1, 1)              | Moderate vanishing gradients                | Xavier Initialization       |
| ReLU                | [0, ∞)               | Dead neurons (if misused)                   | Kaiming (He) Initialization |
| Leaky ReLU          | (-∞, ∞)              | Slight negative slope prevents dead neurons | Kaiming Initialization      |
| GELU                | Smooth non-linearity | Used in modern architectures                | Kaiming Initialization      |

---

##  Why Initialization Matters

Initialization ensures that:

* Activations maintain reasonable variance across layers
* Gradients neither vanish nor explode

### Key Principles:

* **Xavier Initialization** → suited for Sigmoid/Tanh
* **Kaiming Initialization** → suited for ReLU-based activations

---

##  What We Will Measure

During training, we will track:

1. **Training Loss**

   * Convergence speed
   * Stability

2. **Gradient Norms (`param.grad.norm()`)**

   * Strength of gradient flow
   * Layer-wise learning behavior

---

##  Key Questions

For each activation, we will analyze:

* Does the loss decrease efficiently?
* Do gradients vanish in early layers?
* Are gradients stable across layers?
* How fast does the model converge?

---

##  Expected Behavior

| Activation | Expected Outcome                          |
| ---------- | ----------------------------------------- |
| Sigmoid    | Slow learning, strong vanishing gradients |
| Tanh       | Better than sigmoid, but still vanishing  |
| ReLU       | Stable training, strong gradient flow     |
| Leaky ReLU | Improved stability over ReLU              |
| GELU       | Smooth and stable (modern architectures)  |

---

##  Key Insight Goal

> Understand how **activation function + initialization together control gradient flow and training success**.

---

##  Final Goal

By the end of this notebook, we should be able to answer:

* Why Sigmoid is rarely used in deep networks
* Why ReLU became dominant
* How to choose activation functions in practice
* How gradient behavior changes across architectures

---
"""

# imports
import 
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# simple classification dataset
N = 200
X = torch.randn(N,2)
y = (X[:,0] + X[:,1]>0).long() # why long?? CrossEntropyLoss requires class labels as integers (LongTensor), not boolean values.

# deep neural network creation
def create_deep_model():

 layers=[]
 input_dim = 2

 for _ in range(10):      # after for we need a variable in python thats why _ as we dont carfe about this variable
   layers.append(nn.Linear(input_dim , 64))
   layers.append(nn.LeakyReLU())
   input_dim = 64

 layers.append(nn.Linear(64,2))
 return nn.Sequential(*layers) # *layers = unpack list into separate layers which for loop created so PyTorch can build the network correctly

# # Xavier initilisation
# def init_xavier(model):
#   for layer in model:
#     if isinstance(layer,nn.Linear):
#       nn.init.xavier_normal_(layer.weight)
#       nn.init.zeros_(layer.bias)


# He initialisation
def init_weights(model):
  for layer in model:
   if isinstance(layer,nn.Linear):
      nn.init.kaiming_normal_(layer.weight)
      nn.init.zeros_(layer.bias)

# model initialization
model = create_deep_model()
init_weights(model)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

# Training and Gradient Tracking
gradient_history = []  # A list to store gradients of ALL layers for each epoch
#Structure after training:
#gradient_history = [
# [g1, g2, g3, ..., gN],   # epoch 0
# [g1, g2, g3, ..., gN],   # epoch 1 ,
# ...
#]
for epochs in range (200):
  logits = model(X)
  loss = criterion(logits,y)
  optimizer.zero_grad()
  loss.backward() # computes gradients for all parameters. for each parameter we get param.grad the gradient of the loss with respect to that parameter
                  # So for each parameter: param.grad  ← gets filled automatically

  layer_grad = [ ] # temporary list for current epoch  to collect gradient norms(A single number representing gradient magnitude)

  for name , param in model.named_parameters():   # model.named_parameters  is a PyTorch function that returns:  (name, parameter) for every parameter in the model.
  # name is a string representing the parameter name , Examples: '0.weight','0.bias' ... , Meaning:  layer_index.parameter_type
  # param is actual parameter tensor (weights or bias) , param can be weights of a layer , bias of a layer
  # in crux it loops through ALL learnable parameters in the model .

    if param.grad is not None:   #   safety check sometimes gradients may not exist (rare case)
     layer_grad.append(param.grad.norm().item()) #  param.grad.norm.item() means "How strong is the gradient for this layer?"

  gradient_history.append(layer_grad)
  optimizer.step()


  if epochs % 20 == 0 :
    print(f"Epoch:{epochs}, Loss:{loss.item():.4f}")

# plotting of gradient flow
import numpy as np
gradient_history = np.array(gradient_history) # we have to convert gradient history a python list into array because:
                                              # 1)Python lists DO NOT support multi-dimensional indexing.
                                              # 2)We convert to NumPy array so we can easily access gradients layer-wise using slicing like [:, i] for plotting.
plt.figure(figsize=(6,5))

for i in range(0,gradient_history.shape[1],2): # shape of gradient_history is [200,22] here 22 is no of parameters for 11 layers  and shape[1] signifies no of parameters for these 11 layer layer which is 22.
   plt.plot(gradient_history[:,i], label =f"layer{i}")# 2 is jump means layer 0 then 2 then 4 like this
   plt.xlabel("Epochs")
   plt.ylabel("Gradient Norm")
   plt.title("Gradient flow across layers")
   plt.legend()
   plt.show()

"""#  Final Conclusion: Activation Functions and Gradient Flow

##  Overview

In this experiment, we analyzed the effect of four activation functions — **Sigmoid, Tanh, ReLU, and Leaky ReLU** — on training performance and gradient flow in a deep neural network. The goal was to understand how each activation affects **gradient propagation**, **training stability**, and **convergence behavior**.

---

##  Observations

### 1. **Sigmoid**

* Training loss decreased slowly compared to other activations.
* Gradients became extremely small in deeper layers.
* Strong evidence of **vanishing gradients**, especially due to output saturation.

 **Conclusion**:
Sigmoid suffers severely from vanishing gradients, making it unsuitable for deep networks.

---

### 2. **Tanh**

* Better performance than Sigmoid due to zero-centered outputs.
* Still showed significant gradient decay in deeper layers.
* Vanishing gradient problem persists, though less severe than Sigmoid.

 **Conclusion**:
Tanh improves over Sigmoid but still struggles with vanishing gradients in deep networks.

---

### 3. **ReLU (with He Initialization)**

* Faster convergence and lower training loss than Sigmoid and Tanh.
* Gradients remained stronger across layers but decreased slightly in deeper layers.
* Possible risk of dead neurons, though not dominant here.

 **Conclusion**:
ReLU significantly improves gradient flow and training speed, making it a strong baseline for deep learning.

---

### 4. **Leaky ReLU**

* Achieved the best training loss.
* Maintained strong gradients even in very deep layers.
* Initial large gradients stabilized quickly during training.

 **Conclusion**:
Leaky ReLU provides the most stable and effective gradient flow, avoiding both vanishing gradients and dead neuron issues.

---

##  Comparative Summary

| Activation | Gradient Flow | Training Speed | Stability | Deep Network Suitability |
| ---------- | ------------- | -------------- | --------- | ------------------------ |
| Sigmoid    | Very Poor     | Slow           | Medium    | ❌ Very Low               |
| Tanh       | Poor          | Moderate       | High      | ❌ Low                    |
| ReLU       | Moderate      | Fast           | Good      | ⚠️ Medium–High           |
| Leaky ReLU | Strong        | Fastest        | Very Good | ✅ High                   |

---

##  Final Insight

* **Sigmoid and Tanh** suffer from vanishing gradients, limiting deep network learning.
* **ReLU-based activations** improve gradient propagation and accelerate training.
* **Leaky ReLU** performs best by maintaining non-zero gradients even for negative inputs.
* Proper activation choice is critical for efficient deep learning.

---

##  Final Conclusion

Activation functions play a crucial role in deep neural network performance. Among the tested functions, **Leaky ReLU demonstrated the best performance**, followed by **ReLU**, due to their ability to preserve gradient flow. In contrast, **Sigmoid and Tanh are less effective for deep networks** due to vanishing gradient issues.

---

##  Key Takeaway

> **Avoid saturating activations (Sigmoid, Tanh) in deep networks — prefer ReLU variants for better gradient flow and faster learning.**

"""

