# -*- coding: utf-8 -*-
"""Batch_Normalisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcFIQiCWIpTORThuwGA_tL2vCV7lRNHr

# Batch Normalization

Deep neural networks often suffer from unstable training due to changes in the distribution of activations across layers during training.

This phenomenon is called **Internal Covariate Shift**.

Batch Normalization was introduced to stabilize training by normalizing the activations of each layer.

---

# Internal Covariate Shift

During training, the parameters of earlier layers change continuously.

This causes the input distribution of later layers to shift.

As a result:

* training becomes unstable
* learning slows down
* gradients may explode or vanish

Batch Normalization reduces this effect by keeping activations normalized during training.

---

# Batch Normalization Idea

For a mini-batch of activations:

$$
x_1, x_2, ..., x_m
$$

Compute the batch statistics:

### Batch Mean

$$
\mu_B = \frac{1}{m} \sum_{i=1}^{m} x_i
$$

### Batch Variance

$$
\sigma_B^2 = \frac{1}{m} \sum_{i=1}^{m} (x_i - \mu_B)^2
$$

---

# Normalization Step

Each activation is normalized:

$$
\hat{x}_i = \frac{x_i - \mu_B}{\sqrt{\sigma_B^2 + \epsilon}}
$$

Where:

* $\epsilon$ is a small number for numerical stability.

---

# Learnable Scaling and Shifting

After normalization we apply learnable parameters:

$$
y_i = \gamma \hat{x}_i + \beta
$$

Where:

* $\gamma$ (scale parameter)
* $\beta$ (shift parameter)

These allow the network to learn the optimal activation distribution.

---

# Why Batch Normalization Helps

Batch normalization provides several benefits:

* stabilizes gradient flow
* allows higher learning rates
* speeds up training
* reduces sensitivity to initialization
* acts as a mild regularizer

---

# Goal of This Experiment

We will compare two neural networks:

1. Neural network **without Batch Normalization**
2. Neural network **with Batch Normalization**

We will observe how batch normalization affects training stability and convergence speed.
"""

# imports and data generation
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection  import train_test_split

torch.manual_seed(42)
X = torch.linspace(-10,10,200).reshape(-1,1)
noise= torch.randn_like(X) * 2
true_y = 3*X**2 +2*X+5
y = true_y + noise
#normalisation
X_norm= (X-X.mean(dim=0))/ X.std(dim=0)
y_norm= (y-y.mean(dim=0))/ y.std(dim=0)

from torch.utils.data import TensorDataset , DataLoader
#train test split
X_train,X_test,y_train,y_test= train_test_split(X_norm,y_norm, test_size=0.2,random_state=42)
#creation of dataset objects
train_dataset= TensorDataset(X_train, y_train)
test_datset= TensorDataset(X_test,y_test)


# data loader creation
train_loader = DataLoader(train_dataset, batch_size= 16 ,shuffle =True )
test_loader = DataLoader(test_datset, batch_size= 16, shuffle= False)

# model without batch normalization
def model_without_bn():
  model = nn.Sequential(
    nn.Linear(1,64),
    nn.ReLU(),
    nn.Linear(64,64),
    nn.ReLU(),
    nn.Linear(64,1)
)
  return model

# model with batch normalization
def model_with_bn():
  model = nn.Sequential(
      nn.Linear(1,64),
      nn.BatchNorm1d(64),
      nn.ReLU(),
      nn.Linear(64,64),
      nn.BatchNorm1d(64),
      nn.ReLU(),
      nn.Linear(64,1)
  )
  return model

model ={
    "No_BatchNorm": model_without_bn(),
    "BatchNorm": model_with_bn()
}

criterion= nn.MSELoss()

all_losses = {}
for name , model in model.items():                        # items() converts dictionary into pairs.
  print(f"Training with {name}")


  optimizer = optim.Adam(model.parameters(), lr =0.01)

  losses=[]

  for epochs in range(200):
    running_loss = 0.0
    for batch_X,batch_y in train_loader:
      predictions = model(batch_X)
      loss = criterion(predictions, batch_y)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      running_loss +=loss.item()
    avg_training_loss = running_loss/len(train_loader)
    losses.append(avg_training_loss)

    if epochs % 20 ==0:
      print(f"epoch:{epochs}, loss:{avg_training_loss:.4f}")

  all_losses[name]= losses

#plotting of training loss
plt.figure(figsize=(8,6))

for name , losses in all_losses.items():
  plt.plot(losses, label = name)

plt.xlabel("Epochs")
plt.ylabel("Training Losses")
plt.title("Batch Comparison")
plt.legend()
plt.grid(True)
plt.show()

"""### Observations

In this experiment, the model without Batch Normalization converged faster and achieved lower loss.

This occurs because the task is a simple regression problem with a shallow network.

Batch Normalization introduces additional noise due to batch statistics, which can slow training for small datasets.

However, Batch Normalization becomes extremely useful for deeper networks where it stabilizes gradient flow and accelerates convergence.
"""

