# -*- coding: utf-8 -*-
"""Convolution from scratch (NUMPY).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpyYQG-GQCP2gFS0ki8V8UhEimZSTHKc
"""

# imports
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

# creating a simple medical like image

image = np.array([
    [1,1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1,1],
    [1,1,5,5,5,1,1,1],
    [1,1,5,5,5,1,1,1],
    [1,1,5,5,5,1,1,1],
    [1,1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1,1],
],dtype = float)

print("Original image")
print(image)
print(f"Shape of image:{image.shape}")

# Kernels(filters)

#Edge detector kernels (detects vertical edges)

edge_kernel= np.array([
    [-1,0,1],
    [-2,0,2],
    [-1,0,1],
],dtype = float)

blur_kernel= np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1],
],dtype = float) / 9 # dividing by 9 for normalisation

# implementing convolution manually
def manual_convolution (image, kernel ):
  image_height, image_width = image.shape
  kernel_size= kernel.shape[0]
# output will be small as there is no padding
  output_height = image_height - kernel + 1
  output_width = image_width -kernel + 1

  output = np.zeros(output_height, output_width)

  for i in range(output_height):
    for j in range(output_width):
      # extraction of region under kernel
      region = image[i:i+kernel_size, j:j+kernel_size]
      # element wise sum and multiplication
      output[i,j] = np.sum(region *kernel)

  return output

# applying edge detection
edge_output = manual_convolution(image, edge_kernel)
print( "Edge detection output:")
print(edge_output)

# applying blur
blur_output= manual_convolution(image, blur_kernel)
print("Blur output:")
print(blur_output)

# visualisation
fig, axes  = plt.subplots( 2,3, figsize= (12,8)) # here 2 means 2 rows , 3 means 3 columns.
# original image
axes[0,0].imshow(image, cmap = 'gray')
axes[0,0].set_title("Original image")
axes[0,0].axis('off')
# edge_kernel
axes[0,1].imshow(edge_kernel, cmap ='RdBu_r')
axes[0,1].set_title("edge_kernel")
axes[0,1].axis('off')
# edge_output
axes[0,2].imshow(edge_outpt, cmap='gray')
axes[0,2].set_title("Edge_output")
axes[0,2].axis('off')
# blur kernel
axes[1,0].imshow(blur_kernel,cmap='Blues')
axes[1,0].set_title("Blur_kernel")
axes[1,0].axis('off')
# blur_output
axes[1,1].imshow(blur_output, cmap ='gray')
axes[1,1].set_title("Blur_output")
axes[1,1].axis('off')
# comparison
axes[1,2].imshow(np.abs(edge_output), cmap = 'hot')
axes[1,2].set_title("Edge_output magnitude(shows strong edges)")
axes[1,2].axis('off')

plt.tight_layout()
plt.savefig("convolution_demo.png",dpi=100, bbox_inches="tight")
plt.show()

"""# Edge Detection: Understanding np.abs() and Visualization

## Overview
When we apply edge detection kernels to medical images, we get both **positive and negative values**.
This guide explains why we use `np.abs()` and `cmap='hot'` for proper visualization.

---

## 1. What is `np.abs()`?

### Definition
`abs` = **Absolute Value** → Removes negative signs, keeps only magnitude.

### Why Do We Need It?

The edge detection kernel produces **both positive and negative values**:
- **Positive values** = Edge detected in one direction (intensity increase)
- **Negative values** = Edge detected in opposite direction (intensity decrease)
- **Zero** = No edge

#### Edge Kernel (Sobel)
```python
edge_kernel = [[-1,  0,  1],
               [-2,  0,  2],
               [-1,  0,  1]]
```
This kernel detects changes in intensity by comparing left vs right pixels.

---

## 2. Example: What Happens During Convolution

### Sample Image with Lesion
```python
image = np.array([
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 5, 5, 5, 1, 1, 1],  # ← lesion (bright region)
    [1, 1, 5, 5, 5, 1, 1, 1],
    [1, 1, 5, 5, 5, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
], dtype=float)
```

### Case 1: Edge Going UP (1 → 5)
```text
Position (1, 1) in image:

region = [[1, 1, 1],
          [1, 1, 5],   ← Change from 1 to 5 (upward)
          [1, 5, 5]]

Multiply by kernel:
         [[-1,  0,  1],
          [-2,  0,  2],
          [-1,  0,  1]]

Calculation:
├─ Right side:  (+1)×1 + (+2)×5 + (+1)×5 = 1 + 10 + 5 = +16
├─ Left side:   (-1)×1 + (-2)×1 + (-1)×1 = -1 - 2 - 1 = -4
└─ Total: 16 + (-4) = +12  POSITIVE (edge detected!)
```

### Case 2: Edge Going DOWN (5 → 1)
```text
Position (2, 2) in image:

region = [[1, 5, 5],
          [1, 5, 5],   ← Change from 5 to 1 (downward)
          [1, 1, 1]]

Calculation:
├─ Right side:  (+1)×5 + (+2)×1 + (+1)×1 = 5 + 2 + 1 = +8
├─ Left side:   (-1)×1 + (-2)×5 + (-1)×1 = -1 - 10 - 1 = -12
└─ Total: 8 + (-12) = -4  NEGATIVE (opposite direction!)
```

### Result: Mixed Positive and Negative Values
```python
edge_output = np.array([
    [ 1.5,   2.0,   1.5,   0.0,  -1.5,  -2.0],
    [ 3.2,  12.0,   8.5,  -6.0,  -8.0,  -3.2],
    [-2.1,   9.0,  15.0, -12.0, -10.0,  -1.8],
    [ 1.4,   5.0,   7.0,  -5.0,  -4.0,   1.2],
    [ 0.0,   0.0,   0.0,   0.0,   0.0,   0.0],
    [-1.5,  -2.0,  -1.5,   0.0,   1.5,   2.0],
])

# +15.0 = strong edge (one direction)
# -12.0 = strong edge (opposite direction)
#  0.0  = no edge
```

---

## 3. The Problem: Why We Need np.abs()

### Issue with Negative Values
Matplotlib colormaps cannot display negative numbers properly:

```python
# Without np.abs():
axes[1, 2].imshow(edge_output, cmap='hot')

# Both -15.0 and +15.0 might appear as DARK colors
# You lose information about the magnitude!
# This is WRONG for edge detection visualization
```

### Solution: Convert to Absolute Values
```python
# With np.abs():
axes[1, 2].imshow(np.abs(edge_output), cmap='hot')

# |-15.0| = 15.0 and |+15.0| = 15.0
# Both appear as BRIGHT RED
# You see ALL edges, regardless of direction
```

---

## 4. Before and After np.abs()

### Before: Raw Edge Output
```python
edge_output = np.array([
    [ 1.5,   2.0,   1.5,   0.0,  -1.5,  -2.0],
    [ 3.2,  12.0,   8.5,  -6.0,  -8.0,  -3.2],
    [-2.1,   9.0,  15.0, -12.0, -10.0,  -1.8],
    [ 1.4,   5.0,   7.0,  -5.0,  -4.0,   1.2],
    [ 0.0,   0.0,   0.0,   0.0,   0.0,   0.0],
    [-1.5,  -2.0,  -1.5,   0.0,   1.5,   2.0],
])

# Mix of POSITIVE, NEGATIVE, and ZERO values
# Directional information preserved
# Hard to visualize with standard colormaps
```

### After: Magnitude (Absolute Values)
```python
magnitude = np.abs(edge_output)

magnitude = np.array([
    [ 1.5,   2.0,   1.5,   0.0,   1.5,   2.0],
    [ 3.2,  12.0,   8.5,   6.0,   8.0,   3.2],
    [ 2.1,   9.0,  15.0,  12.0,  10.0,   1.8],
    [ 1.4,   5.0,   7.0,   5.0,   4.0,   1.2],
    [ 0.0,   0.0,   0.0,   0.0,   0.0,   0.0],
    [ 1.5,   2.0,   1.5,   0.0,   1.5,   2.0],
])

# All POSITIVE values!
# 15.0 = strong edge (both directions)
# 12.0 = strong edge (both directions)
#  0.0 = no edge
```

---

## 5. Why cmap='hot' is Perfect for Edges

### Colormap Meaning
```python
axes[1, 2].imshow(np.abs(edge_output), cmap='hot')
```
The `hot` colormap maps values to colors:

```text
Magnitude Value    Color          Meaning
─────────────────────────────────────────────
    0.0          Black           No edge
    5.0          Dark Red        Weak edge
   10.0          Red             Medium edge
   15.0          Bright Red      STRONG edge ← Important!
```

### Visual Interpretation
```text
Original Image with Lesion:
┌──────────────────┐
│                  │
│    ██████        │  ← White region = lesion (value 5)
│    ██████        │     Surrounded by dark region (value 1)
│    ██████        │
│                  │
└──────────────────┘

Edge Output (cmap='hot'):
┌──────────────────┐
│                  │
│  ██████████████  │  ← RED areas = edges
│  ██    ██    ██  │     Where intensity changes from 1→5 or 5→1
│  ██████████████  │     (lesion boundaries)
│                  │
└──────────────────┘

Black = No edge (inside uniform region)
RED = Strong edge (at lesion boundary)  This is what we want!
```
"""

