# -*- coding: utf-8 -*-
"""forcing_overfitting_and_regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUmgLTTD4wKbxMsEx5W3i-EUbhmR21vF

In this file we will force overfitting by training a model of very high capacity on a very small data and  we will plot resut . After that  we will  use dropout and regularisation to handle overfitting.

**SIMPLE NEURAL NETWORK**
"""

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

torch.manual_seed(42)

X= torch.linspace(-10,10,40).reshape(-1,1)
true_y = 3*X**2 + 2*X + 3
noise = torch.randn_like(X) * 8
y = true_y + noise
#normalization for features
X_norm=(X-X.mean(dim =0))/X.std(dim = 0)
# normalisation of target also
y_norm=(y-y.mean())/y.std()          #why normalise output?? Because Neural networks train better when: 1) INPUTS ≈ N(0,1) Outputs ≈ N(0,1)
                                     # OTHERWISE Gradients become large AND Optimization slows

#train_ test_split
X_train, X_test,y_train,y_test = train_test_split(X_norm,y_norm,test_size=0.2,random_state=42)

from torch.nn.modules.activation import ReLU
# neural network
model = nn.Sequential(
    nn.Linear(1,512),
    nn.ReLU(),                              # RELU BRINGS NON LINEARITY TO OUR MODEL
    nn.Linear(512,512),                         #Each ReLU neuron can introduce one piecewise linear boundary, allowing the model to approximate curved functions.
    nn.ReLU(),
    nn.Linear(512,1)

)
criterion= nn.MSELoss()
optimizer = optim.Adam(model.parameters(),lr = 0.005)

# Training loop
training_losses=[]
evaluation_losses=[]

for epoch in range(3000):
 # training
 model.train()
 train_pred = model(X_train)
 train_loss = criterion(train_pred, y_train)

 optimizer.zero_grad()
 train_loss.backward()
 optimizer.step()

 # evaluation
 model.eval()                                           #why we use both model.eval()and torch.no_grad(). Because model.eval() Changes Layer Behavior
 with torch.no_grad():                                  #tells model to switch to evaluation mode , this disable  dropout . what is dropout??
  eval_pred = model(X_test)                             # during training Random neurons are turned off this is dropout so model.eval() disable dropout and all neurons are active now
  eval_loss = criterion(eval_pred,y_test)               #troch.no_grad() tells pytorch not to build the computational graph. effects 1) No gradient tracking 2)Less memory usage
                                                        #3)Faster inference 4)Cannot call .backward() . It affects autograd system only.
                                                        # so both solve different problems

  training_losses.append(train_loss.item())
  evaluation_losses.append(eval_loss.item())

  if epoch % 100 == 0 :
   print (f"Epoch:{epoch},training_loss:{train_loss.item():.4f}, evaluation_loss:{eval_loss.item():.4f}")

#plotting of results
model.eval()
with torch.no_grad():
  test_predictions= model(X_test)
  #sorting of test values for smooth plotting                # we did sorting as train_test_split do random shuffling and curve ploting will not be smooth
  sorted_indices = torch.argsort(X_test.squeeze())           # firstly we did X_test.squeeze what it do X_test SHAPE:(40,1) .squeeze do its shape to (40,) 1 dimension so that argsort can work
                                                             # argsort donot sort it but it provvide index whixh we will use to sort
  X_test_sorted = X_test.squeeze()[sorted_indices]
  y_test_sorted = y_test.squeeze()[sorted_indices]
  test_predictions_sorted= test_predictions.squeeze()[sorted_indices]

  plt.figure(figsize=(8,6))
  plt.scatter(X_test_sorted.numpy(),y_test_sorted.numpy(),label="Test Data",alpha=0.4)
  plt.plot(X_test_sorted.numpy(),test_predictions_sorted.numpy(),label="Model Predictions",linewidth=3)
  plt.legend()
  plt.title("Generalization Of Test Data")
  plt.show()

"""**Objective of Today**

**To understand:**

1. Effect of model capacity (width/depth)

2. Effect of small sample size

3. Effect of noise level

4. Role of L2 regularization

5. Role of Dropout

6. Bias–Variance tradeoff in practice

7. When overfitting actually happens

**Base Problem Setup**

We used a synthetic regression function:

𝑦=
3
𝑥
2
+
2
𝑥
+
3
+
𝜖


Where:

𝜖
∼
𝑁
(
0
,
𝜎
2
)
ϵ∼N(0,σ
2
)

Noise scale was varied (1, 8, etc.)

Sample size was reduced (200 → 40 → 10)

We normalized:

Input features

Target variable

Why normalize?

Because neural networks train better when:

Inputs ≈ N(0,1)

Outputs ≈ N(0,1)

Otherwise:

Gradients become unstable

Optimization slows

Exploding/vanishing behavior increases

**Capacity Experiments**
We tested models of increasing capacity:

Small model:
Linear(1,128) → ReLU → Linear(128,1)

Larger model
Linear(1,512) → ReLU → Linear(512,512) → ReLU → Linear(512,1)

**Observation 1: With large dataset (200 samples)**

Training loss ↓

Evaluation loss ↓

No serious overfitting,
Even large models generalized well

Reason:
Data complexity was simple (quadratic function).
Model capacity >> data complexity did NOT hurt generalization much.

**Observation 2: With small dataset (40 samples, then 10 samples)**

Training loss → almost 0
Evaluation loss → stays higher (~0.014)

This is classic high-variance behavior.
Small data + large model = memorization.

**Regularization Experiments:**
L2 Regularization

**Using:**

optimizer = Adam(..., weight_decay=1e-3)
Equivalent to adding:

𝐿
𝑜
𝑠
𝑠=
𝑀
𝑆
𝐸
+
𝜆
∣
∣
𝑤
∣
∣
2

**Effect:**

Penalizes large weights,
Forces smoother functions,
Reduces overfitting,
Increases bias slightly,

**Observation:**
For simple data:

L2 did NOT improve evaluation loss,
Because base model was already generalizing well

Conclusion: **bold text**
Regularization helps when variance is high.
Not needed when model already generalizes.

                            **Dropout**

Dropout randomly disables neurons during training.

**Effect:**

Prevents co-adaptation,
Acts as model averaging,
Increases training noise,
Reduces variance,

**Observation:**
For small regression problem:

Dropout worsened evaluation slightly,
Because dataset is simple,
Model was not overfitting badly,

**Conclusion:**
Dropout is more useful in:

Large image classification,

NLP,
Deep networks,
High dimensional data,
Not always useful in small regression.

**Noise Experiments**

We increased noise:

noise = torch.randn_like(X) * 8

                      **Observation:**

Training loss decreased,
Evaluation loss stabilized at a higher value,
Model could not reduce error below noise floor,

**Important concept:**

Even perfect model cannot beat noise.
Minimum achievable MSE ≈ variance of noise.


                     **Extreme Overparameterizationt:**

With:

10 samples,
512x512 network,
3000 epochs,

Training loss ≈ 0
Evaluation loss ≈ 0.014

Meaning:

Model memorized training data,
But generalization did not collapse completely.

Why?

Because underlying function is simple (quadratic).
Even large network approximates smooth function.
This is early exposure to:
Modern overparameterized regime
and double descent behavior.

**THEOROTICAL TAKEAWAYS **
 1. Overfitting happens when:

    Model capacity >> effective data information.

2. Regularization is needed when:

    Variance > Bias.

3. Increasing capacity:

    Reduces bias but increases variance.

4. L2:

    Controls magnitude of weights.
    Does not remove parameters.

5. Dropout:

    Introduces stochastic robustness.
    Acts like implicit ensemble.

6. Small dataset + big network:

    Danger zone for high variance.  

7. Bias–Variance Tradeoff:

    Total Error = Bias² + Variance + Noise

    Noise is irreducible.

    Regularization:

    Increases Bias,
    Decreases Variance

    Capacity:

    Decreases Bias,
    Increases Variance
"""

