# -*- coding: utf-8 -*-
"""gradient_flow_and_vanishing_gradients.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxNSKeptg_-m21dyF5xF1-ZC47IQRYbC

# Gradient Flow & Vanishing Gradients

Deep neural networks are trained using **backpropagation**, where gradients flow from the output layer back to earlier layers.

---

## Gradient Flow

During training, gradients update weights:

$$
w = w - \eta \cdot \frac{\partial L}{\partial w}
$$

Each layer receives gradients from the next layer.

---

## The Problem

In deep networks, gradients are repeatedly multiplied during backpropagation:

$$
\frac{\partial L}{\partial w_1} = \frac{\partial L}{\partial w_n} \cdot \prod_{i=1}^{n} \frac{\partial z_i}{\partial z_{i-1}}
$$

This leads to two issues:

---

## 1. Vanishing Gradients

Gradients become **very small**:

$$
\rightarrow 0
$$

Effects:

* Early layers stop learning
* Training becomes very slow
* Deep networks fail to train

---

## 2. Exploding Gradients

Gradients become **very large**:

$$
\rightarrow \infty
$$

Effects:

* Unstable training
* Loss becomes NaN
* Model diverges

---

## Why It Happens

* Sigmoid/Tanh → gradients < 1 → shrink
* Deep chains of multiplication
* Poor weight initialization

---

## Solution Ideas

* ReLU activation
* Proper initialization (He initialization)
* Batch Normalization
* Gradient clipping

---

## Goal of This Experiment

We will:

1. Build a **deep neural network**
2. Track gradient magnitudes at each layer
3. Observe how gradients behave across depth

This helps us understand **why deep learning works (or fails)**.
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# simple classification dataset
N = 200
X = torch.randn(N,2)
y = (X[:,0] + X[:,1]>0).long() # why long?? CrossEntropyLoss requires class labels as integers (LongTensor), not boolean values.

# deep neural network creation
def create_deep_model():

 layers=[]
 input_dim = 2

 for _ in range(10):      # after for we need a variable in python thats why _ as we dont carfe about this variable
   layers.append(nn.Linear(input_dim , 64))
   layers.append(nn.Tanh())
   input_dim = 64

 layers.append(nn.Linear(64,2))
 return nn.Sequential(*layers) # *layers = unpack list into separate layers which for loop created so PyTorch can build the network correctly

# model initialization
model = create_deep_model()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.01)

# Training and Gradient Tracking
gradient_history = []  # A list to store gradients of ALL layers for each epoch
#Structure after training:
#gradient_history = [
# [g1, g2, g3, ..., gN],   # epoch 0
# [g1, g2, g3, ..., gN],   # epoch 1 ,
# ...
#]
for epochs in range (200):
  logits = model(X)
  loss = criterion(logits,y)
  optimizer.zero_grad()
  loss.backward() # computes gradients for all parameters. for each parameter we get param.grad the gradient of the loss with respect to that parameter
                  # So for each parameter: param.grad  ← gets filled automatically

  layer_grad = [ ] # temporary list for current epoch  to collect gradient norms(A single number representing gradient magnitude)

  for name , param in model.named_parameters():   # model.named_parameters  is a PyTorch function that returns:  (name, parameter) for every parameter in the model.
  # name is a string representing the parameter name , Examples: '0.weight','0.bias' ... , Meaning:  layer_index.parameter_type
  # param is actual parameter tensor (weights or bias) , param can be weights of a layer , bias of a layer
  # in crux it loops through ALL learnable parameters in the model .

    if param.grad is not None:   #   safety check sometimes gradients may not exist (rare case)
     layer_grad.append(param.grad.norm().item()) #  param.grad.norm.item() means "How strong is the gradient for this layer?"

  gradient_history.append(layer_grad)
  optimizer.step()


  if epochs % 20 == 0 :
    print(f"Epoch:{epochs}, Loss:{loss.item():.4f}")

"""For each epoch:
    compute gradients using backward()

    for each parameter (weight or bias):
        compute gradient norm (single value)

    store all parameter gradient values

Repeat for all epochs

Also for each layer we have weight and bias as parameter there can be many weight  so this leads to many gradient and param.grad() contains these gradients so param.grad.norm() to get single value.also there is value of bias gradient in gradient_history

so gradient_history for epoch is gradient norm of layer 1 weight , gradient norm for layer 1 bias ...... till layer 11 .

so shape of gradient_history=[200,22]

# Understanding `param.grad` (Core Deep Learning Concept)

---

## What is `param.grad`?

In PyTorch, every learnable parameter (weights and biases) stores its gradient after backpropagation.

$$
\text{param.grad} = \frac{\partial L}{\partial \text{param}}
$$

This means:

> `param.grad` tells us **how the loss changes when the parameter changes**

---

## Two Ways to Understand It

### 1. Mathematical Meaning

$$
\frac{\partial L}{\partial w}
$$

* How sensitive the loss is to that weight
* If this value is large → weight strongly affects loss
* If this value is small → weight has little effect

---

### 2. Implementation Meaning (PyTorch)

```python
param.grad
```

* It is a **tensor**
* Same shape as the parameter
* Stores gradient for **each individual weight**

---

## Example

Suppose:

```text
param (weights) =
[[0.5, -0.2],
 [1.0,  0.3]]
```

After backpropagation:

```text
param.grad =
[[ 0.1, -0.05],
 [ 0.2,  0.0 ]]
```

Meaning:

* 0.1 → small increase in that weight increases loss slightly
* -0.05 → increasing that weight reduces loss
* 0.0 → no effect

---

## Intuition

Think of:

```text
param       → knobs of the model  
param.grad  → tells how to turn each knob
```

---

## How It Is Created

Gradients are computed when we call:

```python
loss.backward()
```

After this:

```python
param.grad  # gets filled automatically
```

---

## Why We Need It

To update weights using gradient descent:

$$
w = w - \eta \cdot \frac{\partial L}{\partial w}
$$

In PyTorch:

```python
optimizer.step()
```

Internally uses:

```python
param = param - lr * param.grad
```

---

## Important Behavior

### 1. Gradients accumulate

```python
param.grad += new_gradient
```

So we must reset them:

```python
optimizer.zero_grad()
```

---

### 2. Same shape as parameter

```text
param.shape      = (64, 2)
param.grad.shape = (64, 2)
```

Each weight has its own gradient.

---

## Why We Use `.norm()`

```python
param.grad.norm()
```

This computes:

$$
||g|| = \sqrt{g_1^2 + g_2^2 + ...}
$$

👉 Converts many gradient values → one number

Meaning:

> "How strong is the gradient for this layer?"

---

## Connection to Vanishing Gradients

In deep networks:

* Output layer → strong gradients
* Early layers → very small gradients

So:

```text
param.grad ≈ 0  → layer not learning
```

This is called:

$$
\text{Vanishing Gradient Problem}
$$

---

## Summary

* `param.grad` = gradient of loss w.r.t parameter
* It is stored as a tensor
* It tells how to update weights
* It is used by optimizer to improve the model

---

## One-Line Intuition

$$
\text{param.grad = "How should this weight change to reduce loss?"}
$$
"""

# plotting of gradient flow
import numpy as np
gradient_history = np.array(gradient_history) # we have to convert gradient history a python list into array because:
                                              # 1)Python lists DO NOT support multi-dimensional indexing.
                                              # 2)We convert to NumPy array so we can easily access gradients layer-wise using slicing like [:, i] for plotting.
plt.figure(figsize=(6,5))

for i in range(0,gradient_history.shape[1],2): # shape of gradient_history is [200,22] here 22 is no of parameters for 11 layers  and shape[1] signifies no of parameters for these 11 layer layer which is 22.
   plt.plot(gradient_history[:,i], label =f"layer{i}")# 2 is jump means layer 0 then 2 then 4 like this
   plt.xlabel("Epochs")
   plt.ylabel("Gradient Norm")
   plt.title("Gradient flow across layers")
   plt.legend()
   plt.show()

"""###  Gradient Flow Analysis (Vanishing Gradient Problem)

In this experiment, we analyzed how gradients flow through a deep neural network with 10 layers using the Tanh activation function.

####  Observations:

- Early layers (near input) show very small gradient values (close to zero).
- Middle layers also have weak gradients with occasional spikes.
- Deeper layers (closer to output) have relatively stronger gradients.
- Large spikes in some layers indicate occasional gradient explosion.
- After some epochs, gradients become almost zero for many layers.

####  Key Issue:

This behavior indicates the **Vanishing Gradient Problem**, where gradients shrink as they are backpropagated through many layers.

####  Explanation:

- The Tanh activation function squashes values between (-1, 1).
- Its derivative is less than 1, so repeated multiplication across layers makes gradients very small.
- As a result, early layers receive almost no learning signal.

####  Impact on Training:

- Early layers stop learning.
- Only last layers get updated effectively.
- Training becomes unstable due to occasional gradient spikes.
- Loss initially decreases but later becomes unstable.

####  Conclusion:

This experiment demonstrates that deep networks with Tanh activation suffer from poor gradient flow, making training inefficient. This motivates the use of better activations like ReLU and proper initialization methods.
"""

