# -*- coding: utf-8 -*-
"""linear_regression_from_scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWAoXbZph-YIMu_4lbzr6TkF_U_7v1gY

**LINEAR RERESSION FROM SCRATCH **
 We will generate data by ourself using the eqn y= 3x+2 and we will add some noise to it so that the data becomes a real life dataset.
And then we will train your deep learning model so that it reach to as near as possible to y = 3x+ 2.
"""

# generating random dataset
import torch
import matplotlib.pyplot as plt
torch.manual_seed(42)
X= torch.linspace(-5,5, 100)
true_w = 3
true_b = 2
y= true_w * X + true_b + torch.randn_like(X)*2        # torch.randn_like(X) * 2 to add noise to dataset

# initializing parameter
w = torch.randn(1, requires_grad = True)           # will give 1 random value to w between (0, 1)
b = torch.randn(1, requires_grad = True )          # will give 1 random value to b between (0, 1)
learning_rate = 0.01

# TRAINING LOOP
losses =[]                            # we creaqte a empty list that will store loss for each iteration
for epoch in range (200):             # 200 iterations
 y_pred = w*X + b
 loss= ((y_pred- y )**2 ).mean()      # calcuating mean square error

 loss.backward()                       #here pytorch  compute dell w and dell b and stores them in w.grad and b.grad
 with torch.no_grad():                  # why torch.no_grad() because we dont want PyTorch to track this update in the graph.
  w -= learning_rate * w.grad         # otherwise PyTorch would try to compute gradients of gradients. and memory will explode.
  b -= learning_rate * b.grad
 w.grad.zero_()                         # we make w.grad and b.grad = 0 so that for next iteration there is no value for them
 b.grad.zero_()                         #otherwise  the value of next w.grad and b.grad will also add these value in it
 losses.append(loss.item())            # adding loss value as python number to list using item() converts tensor to python number
 if epoch % 20 == 0:
  print (f"epoch:{epoch}, loss:{loss.item():.4f}")

