# -*- coding: utf-8 -*-
"""linear_regression_nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0CVGSs0KFJ3-jsB15AIZkz1Xm-FxBOr

**LINEAR REGFRESSION USING PYTORCH**
NOW WE WILL DO LINEAR REGRESSION CODE USING PYTORCH LIBRARIES EARLIER WE DID IT FROM SCRACTH WITHOUT USING LIBRARIES.
"""

# data generation
import torch
import matplotlib.pyplot as plt
import torch.optim as optim
import torch.nn as nn

X= torch.linspace(-5, 5, 100).reshape(-1 , 1)   # -1 (rows dimension): This indicates that the number of rows is unknown or should be automatically determined.
true_w= 3                                       #The program calculates this value by dividing the total number of elements in the original array by the number of columns specified (which is 1).
true_b =2
y = true_w * X + true_b + torch.randn_like(X) *2

#model defining
model = nn.Linear(1, 1)  # this creates y = wx+b
# nn.Linear(no_of_inputs_features, no_of_outputs_features)
# pytorch internally creates model.weight and model.bias and both have requires_grad = true

# loss and optimizer
criterion = nn.MSELoss()
optimizer= optim.SGD( model.parameters(), lr = 0.01)

#training loop
losses = []
for epoch in range (200):
 y_pred = model(X)
 loss = criterion(y_pred, y)
 # setting w.grad and b.grad = 0
 optimizer.zero_grad()
 loss.backward()
 # optimizing of weight and bias
 optimizer.step()

 losses.append(loss.item())
 if epoch % 20 == 0 :
  print(f"epoch:{epoch}, loss: {loss.item():.4f}")

#PRINT LEARNED PRAMETER
w_learned = model.weight.item()
b_learned = model.bias.item()

print ("w=" , w_learned)
print("b =",b_learned )

"""**What shape does nn.Linear expect?**
  nn.Linear(in_features, out_features) expects input of shape:
(
batch_size,in_features
)

So if we define:

model = nn.Linear(1, 1)

It expects input like:

(N, 1)

Meaning:

N samples

1 feature per sample

What shape was X originally?

When you generated:

X = torch.linspace(-10, 10, 100)

Shape of X is:

(100,)
This is a 1D tensor.

It does NOT have a feature dimension.

                **Why reshape to (-1, 1)?**
                
When we do:

It becomes:
(100, 1)

Now:
100 samples
1 feature per sample

Now nn.Linear(1,1) understands it.

                    **Why didn’t we need reshape in scratch case?**

Because in scratch case we did:

y_pred = w * X + b

Here:
w is scalar

b is scalar

X is (100,)

Broadcasting handles it.

No matrix multiplication happening.

It’s element-wise math.

Scratch version:

scalar * vector

Element-wise operation → works with 1D.

nn.Linear version:

Matrix multiply
Needs 2D tensor.

**EFFECTS OF INCRESING NOISE**

If noise variance increases:

(1)Final loss increases
(2)Parameter estimates fluctuate more
(3)Convergence slower
(4)Model stability decreases

But:

If noise mean = 0 → model remains unbiased (on average)

(1)Low Noise + Large Data

Low Bias, Low Variance→ Best case

High Noise
→ High irreducible error

Small Data
→ High variance

Wrong Model
→ High bias
"""

