# -*- coding: utf-8 -*-
"""loss_landscape_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sI16qXlUFg73Y6XKBx-RoYnmAgILYadv

# Loss Landscape Visualization

## Objective

When we train a neural network, the optimizer is navigating a high-dimensional
surface called the **loss landscape**. Understanding this surface is critical
for understanding why training works, why it fails, and why choices like
learning rate and initialization matter so much.

---

## What is the Loss Landscape?

The loss landscape is a function of model parameters:

$$
L(\theta)
$$

where $\theta$ represents all the weights and biases of the network.

For every possible set of weights, there is a corresponding loss value.
Visualizing this surface — even in 1D or 2D slices — reveals the geometry
that the optimizer must navigate.

---

## Key Concepts

### Global Minimum

The lowest possible loss value across all parameter configurations.

$$
\theta^* = \arg\min_\theta L(\theta)
$$

This is the ideal solution, but finding it is generally intractable in high dimensions.

### Local Minimum

A point where loss is lower than nearby points but not globally lowest.

$$
\nabla L(\theta) = 0 \quad \text{and} \quad \nabla^2 L(\theta) \succ 0
$$

The optimizer stops here because gradients are zero, even if better solutions exist.

### Saddle Point (Very Important)

A point where the gradient is zero but it is neither a minimum nor a maximum.

$$
\nabla L(\theta) = 0 \quad \text{but} \quad \nabla^2 L(\theta) \text{ is indefinite}
$$

In high-dimensional networks, saddle points are far more common than local minima.
This is where training often stalls.

### Flat vs Sharp Minima

- **Flat minimum**: Loss changes slowly around this point → model generalizes better
- **Sharp minimum**: Loss changes rapidly around this point → model may overfit

$$
\text{Flat: } \frac{\partial^2 L}{\partial \theta^2} \text{ is small} \qquad
\text{Sharp: } \frac{\partial^2 L}{\partial \theta^2} \text{ is large}
$$

---

## Why This Matters

| Concept | Connection to Loss Landscape |
|---|---|
| Learning rate | Controls step size while navigating |
| Initialization | Determines starting point on the surface |
| Optimizer choice | Determines how we move across the surface |
| Generalization | Flat minima generalize better than sharp ones |
| Training stuck | Model has hit a saddle point or flat region |

---

## Experiment Plan

We will:

1. Train a simple neural network to reach a good region in the landscape
2. Select two model parameters
3. Perturb them systematically around the trained values
4. Measure how the loss changes with each perturbation
5. Visualize the resulting 1D and 2D loss slices

This gives us a window into the geometry the optimizer navigated during training.

---

## Expected Observations

- Near a good minimum: loss forms a bowl shape (U-curve in 1D)
- Sharp minimum: very steep walls on the bowl
- Flat minimum: gradual, wide bowl
- Saddle point region: flat in one direction, curved in another
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
torch.manual_seed(42)

# dataset generation
N = 200
X = torch.randn(N,2)
y = (X[:,0] + X[:,1] > 0).long()
print(f" X Shape:{X.shape}")
print(f" y Shape:{y.shape}")
print(f"Class Distribution: {y.sum().item()} ones , {(y==0).sum().item()} zeros") # y.sum() counts ones because summing 0s and 1s gives the count of 1s, and (y==0).sum() counts zeros by first converting to a boolean mask.

# model generation
model = nn.Sequential(
    nn.Linear(2,16),
    nn.ReLU(),
    nn.Linear(16,16),
    nn.ReLU(),
    nn.Linear(16,2)
)

# Loss and Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 0.05)

# Training loop
losses = []
for epochs in range (200):
  optimizer.zero_grad()
  logits= model(X)
  loss = criterion(logits,y)
  loss.backward()
  optimizer.step()
  losses.append(loss.item())

  if epochs % 20 == 0:
    print(f"Epoch :{epochs} , Training_loss :{loss.item():.4f}")

# plotting of losses
plt.figure(figsize =(6,6))
plt.plot(losses)
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training Loss Plotting")
plt.grid(True)
plt.show()

# parameter selection and storage of weights
param = list(model.parameters())[0]  # model.parameters() returns all learnable parameters in the model [W1, b1 , w2 , b2 ,.....] we convert it to list and took very first parameter which is first layer weight matrix
original_weight = param.data.clone() # storing the original value as we will further gonna change it  if we dont use clone then it will becme reference and as we will change in param so it will also reflec in original_weight so clone prevents this .
print(f"Parameter Shape:{param.data.shape}")

# 1d Loss Landscape
alphas = torch.linspace(-2,2,100)
loss_values_1d =[]
model.eval()
with torch.no_grad():
  for a in alphas:
    param.data = original_weight + a
    logits = model(X)
    loss = criterion(logits,y)
    loss_values_1d.append(loss.item())

param.data = original_weight.clone()

plt.figure(figsize=(8,5))
plt.plot(alphas, loss_values_1d, color = "steelblue", linewidth=2)
plt.axvline(x=0,color="red",linestyle="--",label ="trained position")  # ax stand for axis , v for vertical , line means line ,
plt.xlabel("alpha values")                                             # x=0,Draw the line at x position 0. This is where a = 0, which is the exact trained position because w_original + 0 = w_original.
plt.ylabel("loss")
plt.title("1D Loss Landscape Slice")
plt.legend()
plt.grid(True)
plt.show()

#2d Loss Landscape Slice