# -*- coding: utf-8 -*-
"""Neural_Network_Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jrLqHXTFH1vHsbu8lj9fgVje7olBC44

**SIMPLE NEURAL NETWORK**
"""

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

torch.manual_seed(42)

X= torch.linspace(-10,10,200).reshape(-1,1)
true_y = 3*X**2 + 2*X + 3
noise = torch.randn_like(X)
y = true_y + noise
#normalization for features
X_norm=(X-X.mean(dim =0))/X.std(dim = 0)
# normalisation of target also
y_norm=(y-y.mean())/y.std()          #why normalise output?? Because Neural networks train better when: 1) INPUTS ≈ N(0,1) Outputs ≈ N(0,1)
                                     # OTHERWISE Gradients become large AND Optimization slows

from torch.nn.modules.activation import ReLU
# neural network
model = nn.Sequential(
    nn.Linear(1,32),
    nn.ReLU(),                              # RELU BRINGS NON LINEARITY TO OUR MODEL
    nn.Linear(32,1)                         #Each ReLU neuron can introduce one piecewise linear boundary, allowing the model to approximate curved functions.
)
criterion= nn.MSELoss()
optimizer = optim.Adam(model.parameters(),lr = 0.005)

# Training loop
losses=[]
for epoch in range (1000):          # for neural network no of epochs are generaaly high so that they can learn.
  y_pred = model(X_norm)
  loss = criterion(y_pred, y_norm)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  losses.append(loss.item())
  if epoch % 50 ==0:
    print(f"Epoch:{epoch}, loss:{loss.item():.4f}")

#PLOTTING OF RESULTS
with torch.no_grad():
  predictions =model(X_norm)
  # normalisizing true_y before plotting
  true_y_norm = (true_y - y.mean()) / y.std()

  plt.scatter(X_norm.numpy(),y_norm.numpy(),label = "noise data", alpha = 0.5)
  plt.plot(X_norm.numpy(),true_y_norm.numpy(), label ="true curve", linewidth=3)
  plt.plot(X_norm.numpy(),predictions.numpy(), label ="neural network curve", linewidth = 3)
  plt.legend()
  plt.show()
