# -*- coding: utf-8 -*-
"""nn_optimizer_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwJv85Sjwa1w9UpP_eP09QS4M0LyHcsF

# Optimizer Comparison: SGD vs Momentum vs Adam

In previous experiments we trained neural networks using gradient descent based optimization.  
In this notebook we explore **how different optimizers affect training dynamics**.

The optimizer determines **how model parameters are updated using gradients**.

Understanding optimizers is critical because they influence:

- convergence speed
- training stability
- ability to escape poor minima
- generalization performance

---

# 1. Gradient Descent Recap

Training a neural network means minimizing a **loss function**.

Example loss:

$$
L(\theta)
$$

where:

- $\theta$ = model parameters  
- $L$ = loss function

The gradient of the loss tells us **which direction increases the loss the most**.

$$
\nabla_{\theta} L
$$

To minimize the loss we move in the **opposite direction of the gradient**.

Basic gradient descent update:

$$
\theta = \theta - \eta \nabla_{\theta} L
$$

Where:

- $\eta$ = learning rate

The learning rate controls **step size during optimization**.

If the learning rate is:

Too large → training diverges  
Too small → training becomes extremely slow

---

# 2. Stochastic Gradient Descent (SGD)

Instead of computing gradients using the **entire dataset**, deep learning typically uses **mini-batches**.

This method is called **Stochastic Gradient Descent (SGD)**.

Update rule:

$$
\theta_{t+1} = \theta_t - \eta g_t
$$

where:

- $g_t$ = gradient computed from a mini-batch

Advantages:

- computationally efficient
- introduces gradient noise that can help escape bad minima

Disadvantages:

- noisy updates
- oscillations in steep regions of the loss surface
- slow convergence

SGD often follows a **zig-zag path** in narrow valleys of the loss landscape.

---

# 3. SGD with Momentum

Momentum improves SGD by introducing a **velocity term** that accumulates gradients over time.

Instead of relying only on the current gradient, the optimizer maintains a **moving average of past gradients**.

Velocity update:

$$
v_t = \beta v_{t-1} + g_t
$$

Parameter update:

$$
\theta_{t+1} = \theta_t - \eta v_t
$$

Where:

- $v_t$ = velocity
- $\beta$ = momentum coefficient (typically 0.9)

Intuition:

Momentum behaves like a **ball rolling down a hill**.

Benefits:

- reduces oscillations
- accelerates learning along consistent gradient directions
- faster convergence compared to vanilla SGD

---

# 4. Adam Optimizer

Adam stands for **Adaptive Moment Estimation**.

It combines two important ideas:

1. Momentum (first moment)
2. Adaptive learning rates (second moment)

Adam tracks:

First moment (mean of gradients):

$$
m_t = \beta_1 m_{t-1} + (1-\beta_1) g_t
$$

Second moment (uncentered variance):

$$
v_t = \beta_2 v_{t-1} + (1-\beta_2) g_t^2
$$

The update rule becomes:

$$
\theta = \theta - \eta \frac{m_t}{\sqrt{v_t} + \epsilon}
$$

Where:

- $m_t$ = gradient momentum
- $v_t$ = squared gradient average
- $\epsilon$ = small constant for numerical stability

Typical default hyperparameters:

- learning rate = 0.001
- $\beta_1 = 0.9$
- $\beta_2 = 0.999$

Advantages:

- adaptive learning rate for each parameter
- stable training
- fast convergence

Adam is one of the **most commonly used optimizers in deep learning**.

---

# 5. Key Differences Between Optimizers

| Optimizer | Idea | Pros | Cons |
|-----------|------|------|------|
| SGD | Basic gradient descent | Simple, good generalization | Slow convergence |
| Momentum | Gradient smoothing | Faster and more stable | Requires tuning momentum |
| Adam | Adaptive learning rates + momentum | Very fast convergence | Sometimes worse generalization |

Important observation from research:

Fast optimization **does not always mean better generalization**.

Large models like **ResNet and Vision Transformers** are often trained using **SGD with momentum** rather than Adam.

---

# 6. Goal of This Experiment

In this notebook we will train the **same neural network** using three optimizers:

- SGD
- SGD with Momentum
- Adam

We will observe:

- training loss behavior
- validation loss
- convergence speed

This experiment helps us understand **how optimization algorithms influence neural network training dynamics**.

---

# 7. Experimental Setup

Dataset:

$$
y = 3x^2 + 2x + 3 + noise
$$

Pipeline:

1. Generate dataset
2. Normalize features
3. Train/test split
4. Create TensorDataset
5. Use DataLoader for mini-batch training
6. Train neural network
7. Compare optimizer performance

Neural network architecture:

nn.Sequential(
  
nn.Linear(1, 32),

nn.ReLU(),

nn.Linear(32, 1)
)

Each optimizer will train the model **from scratch** so the comparison is fair.

---

# 8. Expected Observations

SGD:

- slower convergence
- noisier training curve

Momentum:

- faster than SGD
- smoother optimization trajectory

Adam:

- fastest convergence
- very stable training
"""

# imports and data generation
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection  import train_test_split

torch.manual_seed(42)
X = torch.linspace(-10,10,200).reshape(-1,1)
noise= torch.randn_like(X) * 2
true_y = 3*X**2 +2*X+5
y = true_y + 
#normalisation
X_norm= (X-X.mean(dim=0))/ X.std(dim=0)
y_norm= (y-y.mean(dim=0))/ y.std(dim=0)

from torch.utils.data import TensorDataset , DataLoader
#train test split
X_train,X_test,y_train,y_test= train_test_split(X_norm,y_norm, test_size=0.2,random_state=42)
#creation of dataset objects
train_dataset= TensorDataset(X_train, y_train)
test_datset= TensorDataset(X_test,y_test)


# data loader creation
train_loader = DataLoader(train_dataset, batch_size= 8 ,shuffle =True )
test_loader = DataLoader(test_datset, batch_size= 8, shuffle= False)

# model creation                                     # we have to create a model creation function because :
def create_model():                                  # we wnat every optimizer get weights generalised so there is no biasness
  model = nn.Sequential(                             # we are creating model again for different optimizers
    nn.Linear(1,64),
    nn.ReLU(),
    nn.Linear(64,1)
)
  return model

# loss and optimizers  and storage of results
criterion  = nn.MSELoss()

optimizer = {                                                      # this is a dictionary , Structure of a dictionary: key → value
    "SGD": lambda params: torch.optim.SGD(params,lr = 0.01 ),                          # So your dictionary looks like this internally:
    "MOMENTUM": lambda params: torch.optim.SGD(params, lr = 0.01, momentum = 0.9),     # | Key        | Value    |
     "ADAM": lambda params: torch.optim.Adam(params, lr = 0.01)                        # | ---------- | -------- |
                                                                                       # | "SGD"      | function |
}                                                                                      # | "Momentum" | function |
                                                                                       # | "Adam"     | function |
                                                                                       # The value is a function (created using lambda).
 # storage of results
all_training_losses = {}
all_evaluation_losses = {}

# optimizer experiment loop
for name , optimizer_fn in optimizer.items():                        # items() converts dictionary into pairs.
  print(f"Training with {name}")

  model = create_model()
  optimizer = optimizer_fn(model.parameters())

  scheduler = torch.optim.lr_scheduler.StepLR(optimizer , step_size= 50 , gamma= 0.5)

  # training loop

  # we will apply early stopping
  best_eval_loss = float("inf")
  patience = 50
  counter = 0
  best_model_state = 0


  training_losses= []
  evaluation_losses=[]

  for epochs in range(300):
  # training phase
    model.train()
    running_training_loss = 0.0

    for batch_X, batch_Y in train_loader:
      predictions= model(batch_X)
      loss = criterion(predictions,batch_Y)

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      running_training_loss+=loss.item()

    avg_training_loss = running_training_loss/len(train_loader)

    training_losses.append(avg_training_loss)

    #evaluation phase
    model.eval()
    with torch.no_grad():
      running_test_loss=0.0
      for batch_X,batch_Y in test_loader:
          predictions = model(batch_X)
          loss = criterion(predictions,batch_Y)
          running_test_loss+= loss.item()

    avg_test_loss = running_test_loss/len(test_loader)
    evaluation_losses.append(avg_test_loss)

    # Step the lr scheduler
    scheduler.step() # It tells the scheduler:Training finished for one epoch , Then scheduler checks: Has step_size epochs passed? If yes: Reduce learning rate
    current_lr = optimizer.param_groups[0]['lr']# Why we need this?? Because we want to print the learning rate.


    # early stopping logic
    if avg_test_loss < best_eval_loss:
      best_eval_loss = avg_test_loss
      counter = 0
      best_model_state = model.state_dict()
    else:
      counter +=1

    if counter >= patience :
      print(f"early stopping triggered at epoch: {epochs}")
      break

    # printing of losses
    if epochs % 50 == 0:
      print(f"Epoch:{epochs}, LR:{current_lr:.6f}, Training_loss:{avg_training_loss:.6f}, Evaluation_loss:{avg_test_loss:.6f}")
  # restore best model
  if best_model_state is not None:
    model.load_state_dict(best_model_state)
    print("best model weights restored")

 # store results                                          # we are storing results so that we can plot them otherwse only last optimizer which is adam only those looses will be ploted
  all_training_losses[name]= training_losses
  all_evaluation_losses[name]= evaluation_losses

#plotting of training loss
plt.figure(figsize=(8,6))

for name , losses in all_training_losses.items():
  plt.plot(losses, label = name)

plt.xlabel("Epochs")
plt.ylabel("Training Losses")
plt.title("Optimizer Comparison{Training Loss}")
plt.legend()
plt.grid(True)
plt.show()

#Plotting of evaluation loss
plt.figure(figsize=(8,6))

for name , losses in all_evaluation_losses.items():
  plt.plot(losses,label = name)

plt.xlabel("Epochs")
plt.ylabel("Evaluation Loss")
plt.title("Optimizer comparison{Evaluation Loss}")
plt.legend()
plt.grid(True)
plt.show()

"""### Observations from Optimizer Comparison

1. Adam converges the fastest during the early training stages.
2. Momentum achieves the lowest evaluation loss, suggesting better generalization.
3. SGD converges the slowest but remains stable.
4. Early stopping was triggered for Adam as evaluation loss began increasing, indicating overfitting.
5. The learning rate scheduler helped stabilize training after 50 epochs by reducing the learning rate.
6. Adam optimizes faster, but SGD with momentum often generalizes better.

   This is why many large models (ResNet, Vision models) still use SGD + Momentum.

## When Do We Need Sorting While Plotting?

Sorting is required **only when plotting a function of X**.

When the x-values are **not ordered**, sorting ensures the plot shows a smooth and meaningful curve.

However, when the x-axis represents **time or sequence (like epochs)**, sorting should **not** be applied because it would destroy the chronological order.

---

### Key Rule

Sorting is required **only when plotting a function of X**.

---

### Examples

| Plot Type | Sort Required? | Reason |
|-----------|---------------|-------|
| Prediction vs X | ✅ Yes | X values are shuffled after train-test split |
| Dataset visualization | ✅ Yes | Produces a clean curve when plotting functions |
| Loss vs Epoch | ❌ No | Epoch order already represents training progression |
| Accuracy vs Epoch | ❌ No | Temporal sequence must remain unchanged |

---

### Important Insight

Loss curves represent **training dynamics over time**.  
Each point corresponds to a specific **epoch during training**.

If we sorted the losses, the relationship between **epoch and loss would be destroyed**, making the plot meaningless.

Therefore:

- **Sort when plotting functions of X**
- **Do not sort when plotting metrics over time (epochs)**
"""

