# -*- coding: utf-8 -*-
"""Vanishing Gradient Fix (ReLU + He Initialization).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVzCljBWaDA9vJKcUcJOO7A8hR3IYXfS

#  Gradient Flow Fix: ReLU + He Initialization

##  Objective

In this notebook, we aim to understand and fix the **vanishing gradient problem** observed in deep neural networks.

---

##  Background

In the previous experiment, we used:
- Deep neural network (10 layers)
- Tanh activation function

### Observed Issues:
- Gradients became very small in early layers (vanishing gradients)
- Some layers showed unstable spikes (exploding gradients)
- Training loss became unstable after initial improvement
- Early layers stopped learning effectively

---

##  Goal of This Notebook

We will fix these issues by making two key changes:

###  1. Use ReLU Activation
- Avoids saturation problem of Tanh
- Allows gradients to flow better

###  2. Use He Initialization
- Proper weight initialization for ReLU
- Maintains variance of activations across layers

---

##  Experiment Plan

We will:
1. Use the same dataset as before
2. Build a deep neural network (10 layers)
3. Replace Tanh with ReLU
4. Apply He initialization to weights
5. Train using SGD optimizer
6. Track gradient norms across layers
7. Compare results with previous experiment

---

##  Expected Outcome

After applying these fixes, we expect:
- Stable gradient flow across all layers
- No vanishing gradients
- Reduced gradient spikes
- Smooth decrease in training loss
- Better overall learning

---

##  Key Learning

This experiment demonstrates that:

> **Activation functions and weight initialization play a crucial role in training deep neural networks.**
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# simple classification dataset
N = 200
X = torch.randn(N,2)
y = (X[:,0] + X[:,1]>0).long() # why long?? CrossEntropyLoss requires class labels as integers (LongTensor), not boolean values.

# deep neural network creation
def create_deep_model():

 layers=[]
 input_dim = 2

 for _ in range(10):      # after for we need a variable in python thats why _ as we dont carfe about this variable
   layers.append(nn.Linear(input_dim , 64))
   layers.append(nn.ReLU())
   input_dim = 64

 layers.append(nn.Linear(64,2))
 return nn.Sequential(*layers) # *layers = unpack list into separate layers which for loop created so PyTorch can build the network correctly

# He initialisation
def init_weights(model):
  for layer in model:
    if isinstance(layer,nn.Linear):
      nn.init.kaiming_normal_(layer.weight)
      nn.init.zeros_(layer.bias)

# model initialization
model = create_deep_model()
init_weights(model)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

"""###  Initialization and Optimizer Choice

#### Bias Initialization:
We initialize biases to zero using:
`nn.init.zeros_(layer.bias)`

- Bias does not significantly affect gradient flow.
- Initializing it to zero avoids unnecessary randomness.
- The model can learn appropriate bias values during training.

#### Why He Initialization for Weights?
- He initialization ensures proper variance of activations when using ReLU.
- Helps prevent vanishing/exploding gradients.

#### Why SGD instead of Adam?
- SGD is a simple optimizer and shows true gradient behavior.
- Adam adapts learning rates and can hide gradient issues.
- Since this experiment focuses on understanding gradient flow,
  SGD helps clearly observe vanishing or exploding gradients.

#### Conclusion:
We use:
- He initialization → to fix gradient flow
- Zero bias → clean starting point
- SGD → to clearly observe learning dynamics
"""

# Training and Gradient Tracking
gradient_history = []  # A list to store gradients of ALL layers for each epoch
#Structure after training:
#gradient_history = [
# [g1, g2, g3, ..., gN],   # epoch 0
# [g1, g2, g3, ..., gN],   # epoch 1 ,
# ...
#]
for epochs in range (200):
  logits = model(X)
  loss = criterion(logits,y)
  optimizer.zero_grad()
  loss.backward() # computes gradients for all parameters. for each parameter we get param.grad the gradient of the loss with respect to that parameter
                  # So for each parameter: param.grad  ← gets filled automatically

  layer_grad = [ ] # temporary list for current epoch  to collect gradient norms(A single number representing gradient magnitude)

  for name , param in model.named_parameters():   # model.named_parameters  is a PyTorch function that returns:  (name, parameter) for every parameter in the model.
  # name is a string representing the parameter name , Examples: '0.weight','0.bias' ... , Meaning:  layer_index.parameter_type
  # param is actual parameter tensor (weights or bias) , param can be weights of a layer , bias of a layer
  # in crux it loops through ALL learnable parameters in the model .

    if param.grad is not None:   #   safety check sometimes gradients may not exist (rare case)
     layer_grad.append(param.grad.norm().item()) #  param.grad.norm.item() means "How strong is the gradient for this layer?"

  gradient_history.append(layer_grad)
  optimizer.step()


  if epochs % 20 == 0 :
    print(f"Epoch:{epochs}, Loss:{loss.item():.4f}")

# plotting of gradient flow
import numpy as np
gradient_history = np.array(gradient_history) # we have to convert gradient history a python list into array because:
                                              # 1)Python lists DO NOT support multi-dimensional indexing.
                                              # 2)We convert to NumPy array so we can easily access gradients layer-wise using slicing like [:, i] for plotting.
plt.figure(figsize=(6,5))

for i in range(0,gradient_history.shape[1],2): # shape of gradient_history is [200,22] here 22 is no of parameters for 11 layers  and shape[1] signifies no of parameters for these 11 layer layer which is 22.
   plt.plot(gradient_history[:,i], label =f"layer{i}")# 2 is jump means layer 0 then 2 then 4 like this
   plt.xlabel("Epochs")
   plt.ylabel("Gradient Norm")
   plt.title("Gradient flow across layers")
   plt.legend()
   plt.show()

"""#  Observations: Gradient Flow & Training Behavior

##  1. Loss Behavior

* The loss decreased smoothly from **0.86 → 0.02**
* This indicates that the model learned effectively and converged properly
* No sudden spikes or instability were observed

---

##  2. Gradient Flow Across Layers

* Gradients were **high at the beginning** of training
* Over time, gradients **gradually decreased**
* This shows normal learning behavior:

  * Early phase → large updates (fast learning)
  * Later phase → small updates (fine tuning)

---

##  3. Vanishing Gradient Analysis

* Gradients did **not become zero in early epochs**
* All layers received meaningful gradient signals
* Therefore, **no severe vanishing gradient problem** was observed

---

##  4. Effect of Proper Initialization

* Kaiming Initialization helped maintain stable gradient flow
* Prevented:

  * Extremely small gradients (vanishing)
  * Extremely large gradients (exploding)
* Enabled efficient training of a deep network

---

##  5. Layer-wise Gradient Behavior

* Gradient trends were **similar across layers**
* Indicates that gradients are flowing properly through the entire network
* No layer became inactive or "dead"

---

##  6. Overall Conclusion

* The network trained successfully with **stable gradient flow**
* Proper initialization + ReLU activation ensured:

  * Efficient learning
  * No gradient instability
* This experiment demonstrates how to **diagnose and verify gradient flow in deep networks**

---

##  Key Takeaway

> Monitoring `param.grad.norm()` is a powerful way to understand how learning happens inside a neural network.

"""

